name: Test Docker Image build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
      with:
        python-version: '3.10'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7

    - name: Build and push
      uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      with:
        context: .
        push: false
        tags: |
            ghcr.io/vmware/repository-service-tuf-api:test
        build-args: |
          RELEASE_VERSION=test
